
LOCATIONS = [
    {
        "name": "the library",
        "block_location": "horizontals/Juniper St blocks/2000-2099 Juniper St",
        "address": "2025 Juniper St - the library",
        "exit_name": "front door",
        "marker": "[ the library ]",
        "objects": [
            {"path": "fiction books/a brief history of map quests"},
            {"path": "fiction books/home, again"},
            {"path": "fiction books/deep ocean"},
            {"path": "fiction books/hello ily"},
            {"path": "fiction books/goblin tomb 2"},
            {"path": "fiction books/lost in the woods"},
            {"path": "fiction books/one more time"},
            {"path": "nonfiction books/the second house"},
            {"path": "nonfiction books/in too deep- a true story of the ultimate unsinkable submarine"},
            {"path": "nonfiction books/how to identify animal bites"},
            {"path": "nonfiction books/nobody knows"},
            {"path": "nonfiction books/snakes"},
            {"path": "nonfiction books/what's that sound?"},
        ]
    },
    {
        "name": "california drive park",
        "block_location": "verticals/California Dr blocks/300-399 California Dr",
        "address": "301 California Dr - california drive park",
        "exit_name": "sidewalk",
        "marker": "[ california drive park ]",
        "objects": [
            {"path": "tree", "min": 1, "max": 15, "chance": 0.1},
            {"path": "shrub", "min": 32, "max": 85, "chance": 0.05},
            {"path": "postcard"},
            {"path": "trashcan/compostable plastic utensils"},
            {"path": "trashcan/paper plates"},
            {"path": "trashcan/garbage"},
            {"path": "park bench dedicated to gideon"},
            {"path": "park bench dedicated to the ghosts"},
            {"path": "public bathroom/toilet"},
            {"path": "public bathroom/sink"},
            {"path": "public bathroom/shattered mirror"},
        ]
    },
    {
        "name": "market deli",
        "block_location": "verticals/Market Ave blocks/600-699 Market Ave",
        "address": "662 Market Ave - market deli",
        "exit_name": "front door",
        "marker": "[ market deli ]",
        "objects": [
            {"path": "refrigerator/lemonade", "min": 15, "max": 30, "chance": 0.125},
            {"path": "refrigerator/iced_coffee", "min": 10, "max": 25, "chance": 0.25},
            {"path": "freezer/popsicle", "min": 10, "max": 25, "chance": 0.25},
            {"path": "garbage can/popsicle_stick", "min": 1, "max": 100, "chance": 0.03},
            {"path": "garbage can/empty_cup", "min": 1, "max": 100, "chance": 0.03},
            {"path": "sandwhich counter/sandwhich", "min": 25, "max": 55, "chance": 0.25},
            {"path": "chair", "min": 1, "max": 8, "chance": 1.0},
            {"path": "cash register", "count": 1},
            {"path": "muted tv", "count": 1},
            {"path": "table", "count": 2},
        ]
    },
    {
        "name": "rosenberg botanicals",
        "block_location": "horizontals/Willow St blocks/1900-1999 Willow St",
        "address": "1981 Willow St - rosenberg botanicals",
        "exit_name": "front door",
        "marker": "[ rosenberg botanicals ]",
        "objects": [
            {"path": "bouquets/ornate_bouquet", "min": 1, "max": 5, "chance": 0.75},
            {"path": "bouquets/simple_bouquet", "min": 3, "max": 10, "chance": 0.75},
            {"path": "bouquets/assorted_roses", "min": 3, "max": 6, "chance": 0.75},
            {"path": "bouquets/assorted_tulips", "min": 3, "max": 7, "chance": 0.75},
            {"path": "potted plants/small_succulent", "min": 5, "max": 15, "chance": 0.5},
            {"path": "potted plants/snakeplant", "min": 5, "max": 15, "chance": 0.4},
            {"path": "potted plants/small_fern", "min": 2, "max": 10, "chance": 0.6},
            {"path": "seed packs/carrot_seeds", "min": 1, "max": 15, "chance": 0.4},
            {"path": "seed packs/parsley_seeds", "min": 1, "max": 15, "chance": 0.4},
            {"path": "seed packs/thyme_seeds", "min": 1, "max": 15, "chance": 0.4},
            {"path": "seed packs/tomato_seeds", "min": 1, "max": 15, "chance": 0.4},
            {"path": "seed packs/beet_seeds", "min": 1, "max": 15, "chance": 0.4},
            {"path": "seed packs/onion_seeds", "min": 1, "max": 15, "chance": 0.4},
            {"path": "seed packs/cucumber_seeds", "min": 1, "max": 15, "chance": 0.4},
            {"path": "storeroom/seed of wonder"},
            {"path": "cash register"},
        ],
    },
    {
        "name": "the observatory",
        "block_location": "horizontals/Oak St blocks/2200-2299 Oak St",
        "address": "2222 Oak St - the observatory",
        "exit_name": "front gate",
        "marker": "[ the observatory ]",
        "objects": [
            {"path": "telescope"},
            {"path": "research papers/black hole theories"},
            {"path": "research papers/astronomical charts"},
            {"path": "control room/switchboard"},
            {"path": "control room/old radio transmitter"},
            {"path": "storage room/spare telescope lens"},
            {"path": "notepad with cryptic star coordinates"},
            {"path": "gift shop/souvenir_moon_rock", "min": 1, "max": 5, "chance": 0.5},
            {"path": "gift shop/comet_postcard", "min": 1, "max": 10, "chance": 0.6},
            {"path": "gift shop/moon_phase_postcard", "min": 1, "max": 10, "chance": 0.6},
            {"path": "gift shop/star_earrings", "min": 1, "max": 5, "chance": 0.5},
        ],
    },
    {
        "name": "rooftop café",
        "block_location": "verticals/Sunset Ln blocks/300-399 Sunset Ln",
        "address": "350 Sunset Ln - rooftop café",
        "exit_name": "exit stairwell",
        "marker": "[ rooftop café ]",
        "objects": [
            {"path": "barista counter/espresso machine"},
            {"path": "table/croissant"},
            {"path": "table/cup of coffee (half empty)"},
            {"path": "shelf/poetry book"},
            {"path": "lost and found/scarf"},
            {"path": "patio/telescope"},
            {"path": "patio/table for two"},
            {"path": "balcony/viewfinder (out of order)"},
            {"path": "balcony/viewfinder"},
        ],
    },
    {
        "name": "underground bunker",
        "block_location": "horizontals/Chestnut St blocks/2100-2199 Chestnut St",
        "address": "2150 Chestnut St - underground bunker",
        "exit_name": "steel door",
        "marker": "[ underground bunker ]",
        "objects": [
            {"path": "control room/flickering light"},
            {"path": "radio equipment/static hum"},
            {"path": "food storage/canned_beans", "min": 10, "max": 30, "chance": 0.7},
            {"path": "sleeping quarters/bunk bed"},
            {"path": "abandoned diary"},
            {"path": "generator (low power)"},
            {"path": "emergency exit (sealed shut)"},
        ],
    },
]
